// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrsFtOAS6ci_9TzMuZvQuN_XXWtxoMGlE',
    appId: '1:323431876456:web:804dfbed0925bca13b38dd',
    messagingSenderId: '323431876456',
    projectId: 'fir-flutter-codelab-96230',
    authDomain: 'fir-flutter-codelab-96230.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-96230.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuwljROsJd09Gjh8MEmFUGQ7YZ5XpZxC4',
    appId: '1:323431876456:android:82ecceaa113123b83b38dd',
    messagingSenderId: '323431876456',
    projectId: 'fir-flutter-codelab-96230',
    storageBucket: 'fir-flutter-codelab-96230.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0H0NZ08AufAp_FOOOBWp3S-kkdrPcia0',
    appId: '1:323431876456:ios:9cd5429767ebab3c3b38dd',
    messagingSenderId: '323431876456',
    projectId: 'fir-flutter-codelab-96230',
    storageBucket: 'fir-flutter-codelab-96230.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0H0NZ08AufAp_FOOOBWp3S-kkdrPcia0',
    appId: '1:323431876456:ios:9cd5429767ebab3c3b38dd',
    messagingSenderId: '323431876456',
    projectId: 'fir-flutter-codelab-96230',
    storageBucket: 'fir-flutter-codelab-96230.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
